### ISSUE TITLE
No actions when filter empty

### ISSUE THREAD

**Issue by DenisCarriere** [dfuse-io/example-firehose-eosio-nodejs#3]
when setting flag:

```javascript
include_filter_expr: '',
```

Blocks: 150000000 => 150000002

```bash
Block #150000000 (08f0d1801685add3407cce1d753716e2edcf771af5ea3499f5dd476bc8f9a522, irreversible) - 0 Transactions, 0 Actions (0 System Actions)
Block #150000001 (08f0d181b6a25010842df92563e169c4d4b91817e4eda5baa9dcd243c99822bc, irreversible) - 0 Transactions, 0 Actions (0 System Actions)
Block #150000002 (08f0d182c5d91f74bed4f0dbb0d82f7ee027332d13019efa5fcd9c50d59afef9, irreversible) - 0 Transactions, 0 Actions (0 System Actions)
Completed
```

**Comment by maoueh** [comment]
Not sure what to say, what an empty include filter should do exactly? I think it's an OK behavior, including nothing gives nothing.

More a documentation issue IMO.

**Comment by DenisCarriere** [comment]
The issue is when you remove the filter, it also returns nothing 

how do you receive the entire block without filtering?

**Comment by DenisCarriere** [comment]
Probably more documentation would help, this one might be a user error 😅

**Comment by maoueh** [comment]
> The issue is when you remove the filter, it also returns nothing

Ok so you mean that specifying neither of `include_filter_expr` or `exclude_filter_expr` leads to nothing being emitted? If that's the case, that's indeed a problem, was not designed to be like that.

The value `*` should work to include everything unfiltered, so `include_filter_expr: *`.
